Easycase.Web/Models/AccountViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Easycase.Web.Models
{
    public class ExternalLoginConfirmationViewModel
    {
        [Required]
        [Display(Name = "Email")]
        public string Email { get; set; }
    }

    public class ExternalLoginListViewModel
    {
        public string ReturnUrl { get; set; }
    }

    public class SendCodeViewModel
    {
        public string SelectedProvider { get; set; }
        public ICollection<System.Web.Mvc.SelectListItem> Providers { get; set; }
        public string ReturnUrl { get; set; }
        public bool RememberMe { get; set; }
    }

    public class VerifyCodeViewModel
    {
        [Required]
        public string Provider { get; set; }

        [Required]
        [Display(Name = "Code")]
        public string Code { get; set; }
        public string ReturnUrl { get; set; }

        [Display(Name = "Remember this browser?")]
        public bool RememberBrowser { get; set; }

        public bool RememberMe { get; set; }
    }

    public class ForgotViewModel
    {
        [Required]
        [Display(Name = "Email")]
        public string Email { get; set; }
    }

    public class LoginViewModel
    {
        [Required]
        [Display(Name = "Email")]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }

    public class RegisterViewModel
    {
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class ResetPasswordViewModel
    {
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }

        public string Code { get; set; }
    }

    public class ForgotPasswordViewModel
    {
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }
    }
}

Easycase.Web/Controllers/SettingController.cs
using Easycase.Model.Case;
using Easycase.Model.Company;
using Easycase.Model.Setting;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Easycase.Web.Controllers
{
    [Authorize]
    [HandleError]
    public class SettingController : BaseController
    {
        BLCompanyDetail companyDetail = new BLCompanyDetail();
        BLSupport bLsupport = new BLSupport();
        BLCaseType bLCaseType = new BLCaseType();
        BLCaseStatus caseStatus = new BLCaseStatus();
        BLServiceFee serviceFee = new BLServiceFee();
        // GET: Setting
        public ActionResult Index()
        {
            ViewData["SuccessCompany"] = TempData["SuccessCompany"];
            ViewData["FailedCompany"] = TempData["FailedCompany"];
            var userId = User.Identity.GetUserId();
            var company = companyDetail.GetById(userId);
            if (company == null)
                company = new BLCompanyDetail();
            var support = bLsupport.GetById(userId);
            if (support == null)
                company.bLSupport = new BLSupport();
            else
                company.bLSupport = support;
            return View(company);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(BLCompanyDetail client)
        {
            if (ModelState.IsValid)
            {
                var userId = User.Identity.GetUserId();
                client.CreatedBy = userId;
                if (client.ID > 0)
                {
                    var result = client.Update();
                    if (result.Item1)
                        TempData["SuccessCompany"] = result.Item2;
                    else
                        TempData["FailedCompany"] = result.Item2;
                }
                else
                {
                    var result = client.Save();
                    if (result.Item1)
                        TempData["SuccessCompany"] = result.Item2;
                    else
                        TempData["FailedCompany"] = result.Item2;
                }
                return RedirectToAction("Index");
            }
            return View(client);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Support(BLSupport bLSupport)
        {
            if (ModelState.IsValid)
            {
                var userId = User.Identity.GetUserId();
                bLSupport.CreatedBy = userId;
                if (bLSupport.ID > 0)
                {
                    var result = bLSupport.Update();
                    if (result.Item1)
                        TempData["SuccessCompany"] = result.Item2;
                    else
                        TempData["FailedCompany"] = result.Item2;
                }
                else
                {
                    var result = bLSupport.Save();
                    if (result.Item1)
                        TempData["SuccessCompany"] = result.Item2;
                    else
                        TempData["FailedCompany"] = result.Item2;
                }
                return RedirectToAction("Index");
            }
            return View(bLSupport);
        }
        #region Casetype    
        public ActionResult CaseTypeList()
        {
            var caseTypes = bLCaseType.GetAll();
            return View(caseTypes);
        }

        public ActionResult AddNewCaseType(string name,long id) 
        {
            var userId = User.Identity.GetUserId();
            var result = bLCaseType.Save(name, userId,id);
            return Json(result.Item2, JsonRequestBehavior.AllowGet);
        }
        public ActionResult PartialCaseTypeList() 
        {
            var caseTypes = bLCaseType.GetAll();
            return PartialView("_partialCaseTypeList", caseTypes);
        }
        public ActionResult DeleteCaseType(long id)
        {
            bool status = false;
            if (id > 0)
                status = bLCaseType.Delete(id);
            return Json(status, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region CaseStatus    
        public ActionResult CaseStatusList()
        {
            var _caseStatus = caseStatus.GetAll();
            return View(_caseStatus);
        }

        public ActionResult AddNewCaseStatus(string name, long id)
        {
            var userId = User.Identity.GetUserId();
            var result = caseStatus.Save(name, userId, id);
            return Json(result.Item2, JsonRequestBehavior.AllowGet);
        }
        public ActionResult PartialCaseStatusList()
        {
            var _caseStatus = caseStatus.GetAll();
            return PartialView("_partialCaseStatusList", _caseStatus);
        }
        public ActionResult DeleteCaseStatus(long id)
        {
            bool status = false;
            if (id > 0)
                status = caseStatus.Delete(id);
            return Json(status, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Service Fee
        public ActionResult ServiceFee()
        {
            var serviceFees = serviceFee.GetAll();
            return View(serviceFees);
        }
        public ActionResult AddServiceFee(BLAddServiceFee bLAddServiceFee) 
        {
            var userId = User.Identity.GetUserId();
            bLAddServiceFee.CreatedBy = userId;
            var result = bLAddServiceFee.Save();
            return Json(result.Item2, JsonRequestBehavior.AllowGet);
        }
        public ActionResult PartialServiceFee()
        {
            var serviceFees = serviceFee.GetAll();
            return PartialView("_partialServiceFeeList", serviceFees);
        }
        public ActionResult DeleteServiceFee(long id)
        {
            bool status = false;
            if (id > 0)
                status = serviceFee.Delete(id);
            return Json(status, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Client Account
        public ActionResult Account() 
        {
            var userId = User.Identity.GetUserId();
            BLClientAccount bLClientAccount = new BLClientAccount();
            bLClientAccount = bLClientAccount.GetByUserId(userId);
            bLClientAccount.CurrencyArray = JsonConvert.DeserializeObject<string[]>(bLClientAccount.Currency);
            bLClientAccount.BankNameArray = JsonConvert.DeserializeObject<string[]>(bLClientAccount.BankName);
            return View(bLClientAccount);
        }
        [HttpPost]
        public ActionResult Account(BLClientAccount bLClientAccount)
        {
            var userId = User.Identity.GetUserId();
            bLClientAccount.CreatedBy = userId;
            bLClientAccount.BankName = JsonConvert.SerializeObject(bLClientAccount.BankNameArray);
            bLClientAccount.Currency= JsonConvert.SerializeObject(bLClientAccount.CurrencyArray);
            var result= bLClientAccount.Save();
            return Json(result.Item2, JsonRequestBehavior.AllowGet);
        }
        public ActionResult PartialClientAccount()
        {
            var userId = User.Identity.GetUserId();
            BLClientAccount bLClientAccount = new BLClientAccount();
            bLClientAccount = bLClientAccount.GetByUserId(userId);
            bLClientAccount.CurrencyArray = JsonConvert.DeserializeObject<string[]>(bLClientAccount.Currency);
            bLClientAccount.BankNameArray = JsonConvert.DeserializeObject<string[]>(bLClientAccount.BankName);
            return PartialView("_partialAccount", bLClientAccount);
        }
        #endregion
        #region TaxInformation
        public ActionResult Tax()
        {
            var userId = User.Identity.GetUserId();
            BLTaxInformation bLTaxInformation = new BLTaxInformation();
            bLTaxInformation = bLTaxInformation.GetByUserId(userId);
            return View(bLTaxInformation);
        }
        [HttpPost]
        public ActionResult Tax(BLTaxInformation bLTaxInformation)
        {
            if (ModelState.IsValid)
            {
                var userId = User.Identity.GetUserId();
                bLTaxInformation.UserId = userId;
                bLTaxInformation.Save();
            }
            return View(bLTaxInformation);
        }
        #endregion
    }
}

Easycase.Web/Views/Setting/Account.cshtml
@model Easycase.Model.Setting.BLClientAccount

@{
    ViewBag.Title = "Account";
    Layout = "~/Views/Shared/_LayoutSetting.cshtml";
}

<div class="page-breadcrumb">
    <div class="row">
        <div class="col-12 d-flex no-block align-items-center">
            <h4 class="page-title">Client Account(s)</h4>
            <div class="ml-auto text-right">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Library</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<!-- ============================================================== -->
<!-- End Bread crumb and right sidebar toggle -->
<!-- ============================================================== -->
<!-- ============================================================== -->
<!-- Container fluid  -->
<!-- ============================================================== -->
<div class="container-fluid">
    <!-- ============================================================== -->
    <!-- Start Page Content -->
    <!-- ============================================================== -->
    <div class="card">
        <div class="card-body wizard-content">
            <h4 class="card-title"></h4>
            <h6 class="card-subtitle"></h6>
            @using (Html.BeginForm("Account", "Setting", FormMethod.Post, new { @id = "example-form" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "form-horizontal" })
                <div class="form-group row">
                    <div class="col-sm-12" id="clientAccountDiv">
                        @Html.Partial("_partialAccount",Model)
                    </div>
                </div>
                <div class="border-top row">
                    <div class="row position-right">
                        <input type="button" value="Save" onclick="Save()" class="btn btn-info" style="margin-left:10px" />
                    </div>
                </div>

            }
        </div>

    </div>
</div>
@section Scripts {
    <script>
        $(document).ready(function () {
            $(".navigationli").removeClass("selected");
            $("#clientaccountli").addClass("selected");
        });
        function AddRow() {
            var totalTr = $("#bankDetails tbody tr").length;
            var totalTrplus1 = totalTr + 1;
            $("#bankDetails tbody").append('<tr class="education-list-item-' + totalTrplus1 + '" data-row-id="' + totalTr + '">' +
                '<td><input type="text" class="form-control data-bank"></td>' +
                '<td><input type="text" class="form-control data-currency"></td>' +
                '<td class="remove-control" style="width:20px">' +
                '<i class="fa fa-minus-circle" style="color:red" onclick="RemoveRow(this)" aria-hidden="true"></i>' +
                '</td>' +
                '</tr>');
        }
        function RemoveRow(currentrow)
        {
            $(currentrow).parent().parent().remove();
        }
        function GetAccount() {
            $.ajax({
                url: "/Setting/PartialClientAccount",
                type: "POST",
                success: function (response) {
                    $("#clientAccountDiv").html(response);
                },
                error: function (er) {
                    toastr.error(er, 'Error');
                }
            });
        }
        function Save() {
            var obj = new Object();
            var dataBank = [];
            var dataCurrency = [];
            $("#bankDetails tbody tr").each(function (index, value) {
                if ($(value).find(".data-bank").val() != "") {
                    dataBank.push($(value).find(".data-bank").val());
                    dataCurrency.push($(value).find(".data-currency").val());
                }
            });
            obj.ID=@Model.ID;
            obj.BankNameArray = dataBank;
            obj.CurrencyArray = dataCurrency;
            //

            $.ajax({
                url: "/Setting/Account",
                type: "POST",
                data: obj,
                success: function (response) {
                    toastr.success(response, 'Success');
                    GetAccount();
                },
                error: function (er) {
                    toastr.error(er, 'Error');
                }
            });
        }
    </script>
}

Easycase.Web/Views/Setting/Index.cshtml
@model Easycase.Model.Company.BLCompanyDetail
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutSetting.cshtml";
}

<div class="page-breadcrumb">
    <div class="row">
        <div class="col-12 d-flex no-block align-items-center">
            <h4 class="page-title"></h4>
            <div class="ml-auto text-right">
                <nav aria-label="breadcrumb">
                    @*<ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/client/index">Client</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Create</li>
                    </ol>*@
                </nav>
                @*<a href="/client/index" class="btn btn-dark btn-sm">Back</a>*@
            </div>
        </div>
    </div>
</div>
<!-- ============================================================== -->
<!-- End Bread crumb and right sidebar toggle -->
<!-- ============================================================== -->
<!-- ============================================================== -->
<!-- Container fluid  -->
<!-- ============================================================== -->
<div class="container-fluid">
    <!-- ============================================================== -->
    <!-- Start Page Content -->
    <!-- ============================================================== -->
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                @using (Ajax.BeginForm("Index", "Setting",
new AjaxOptions
{
OnSuccess = "OnSuccess",
OnFailure = "OnFailure"
}))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "form-horizontal" })
                    @Html.HiddenFor(model => model.ID)
                <div class="card-body">
                    <h4 class="card-title">Company Contact Details</h4>
                    <div class="form-group row">
                        <div class="col-sm-6">
                            <label class="control-label col-md-6">First Name <span class="required">*</span></label>
                            <div class="col-sm-12">
                                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control", placeholder = "First Name", maxlength = "200" } })
                                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <label class="control-label col-md-6">Last Name <span class="required">*</span></label>
                            <div class="col-sm-12">
                                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control", placeholder = "Last Name", maxlength = "200" } })
                                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-6">
                            <label class="control-label col-md-6">Company Name <span class="required">*</span></label>
                            <div class="col-sm-12">
                                @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control", placeholder = "Company name", maxlength = "200" } })
                                @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <label class="control-label col-md-6">Company Email <span class="required">*</span></label>
                            <div class="col-sm-12">
                                @Html.EditorFor(model => model.CompanyEmail, new { htmlAttributes = new { @class = "form-control", placeholder = "Email", maxlength = "200" } })
                                @Html.ValidationMessageFor(model => model.CompanyEmail, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-sm-6">
                            <label class="control-label col-md-6">Address Line 1 <span class="required">*</span></label>
                            <div class="col-sm-12">
                                @Html.TextBoxFor(model => model.AddressLine1, new { @class = "form-control", placeholder = "Address Line 1", maxlength = "500" })
                                @Html.ValidationMessageFor(model => model.AddressLine1, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <label class="control-label col-md-6">Address Line 2 <span class="required">*</span></label>
                            <div class="col-sm-12">
                                @Html.EditorFor(model => model.AddressLine2, new { htmlAttributes = new { @class = "form-control", placeholder = "Address Line 2", maxlength = "500" } })
                                @Html.ValidationMessageFor(model => model.AddressLine2, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-6">
                            <label class="control-label col-md-6">City<span class="required">*</span></label>
                            <div class="col-sm-12">
                                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control", placeholder = "City", maxlength = "100" } })
                                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <label class="control-label col-md-6">Province<span class="required">*</span></label>
                            <div class="col-sm-12">
                                @Html.EditorFor(model => model.Province, new { htmlAttributes = new { @class = "form-control", placeholder = "Province", maxlength = "100" } })
                                @Html.ValidationMessageFor(model => model.Province, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-6">
                            <label class="control-label col-md-6">Country<span class="required">*</span></label>
                            <div class="col-sm-12">
                                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control", placeholder = "Country", maxlength = "100" } })
                                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <label class="control-label col-md-6">Postal Code<span class="required">*</span></label>
                            <div class="col-sm-12">
                                @Html.EditorFor(model => model.PostalCode, new { htmlAttributes = new { @class = "form-control", placeholder = "Postal Code", maxlength = "30" } })
                                @Html.ValidationMessageFor(model => model.PostalCode, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-6">
                            <label class="control-label col-md-6">Telephone<span class="required">*</span></label>
                            <div class="col-sm-12">
                                @Html.EditorFor(model => model.Telephone, new { htmlAttributes = new { @class = "form-control phone-inputmask", placeholder = "Telephone", maxlength = "30" } })
                                @Html.ValidationMessageFor(model => model.Telephone, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-sm-6">
                            @Html.LabelFor(model => model.Fax, htmlAttributes: new { @class = "control-label col-md-6" })
                            <div class="col-sm-12">
                                @Html.EditorFor(model => model.Fax, new { htmlAttributes = new { @class = "form-control", placeholder = "Fax", maxlength = "30" } })
                                @Html.ValidationMessageFor(model => model.Fax, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-6">
                            <label class="control-label col-md-6">Membership Type<span class="required">*</span></label>
                            <div class="col-sm-12">
                                @Html.DropDownListFor(model => model.MembershipType, new List<SelectListItem>
                                    {
                                        new SelectListItem{ Text="Select Status", Value = "" },
                                        new SelectListItem{ Text="Immigration Consultants of Canada Regulatory Council (ICCRC)", Value = "ICCRC" },
                                        new SelectListItem{ Text="Canadian Provincial or Teritorial Law Society", Value = "LAWSOCIETY" },
                                        new SelectListItem{ Text="Chambre des notaires du Quebec", Value = "QUEBEC" },
                                        new SelectListItem{ Text="Student/Pending Membership", Value = "PENDING" },
                                     }, new { @class = "select2 form-control custom-select" })
                                @Html.ValidationMessageFor(model => model.MembershipType, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <label class="control-label col-md-6">Membership Number<span class="required">*</span></label>
                            <div class="col-sm-12">
                                @Html.EditorFor(model => model.MembershipNumber, new { htmlAttributes = new { @class = "form-control", placeholder = "Membership Number", maxlength = "30" } })
                                @Html.ValidationMessageFor(model => model.MembershipNumber, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>
                    <div class="border-top">
                        <div class="card-body">
                            <input type="submit" value="Save" class="btn btn-default" />
                        </div>
                    </div>
                }
            </div>
            <div class="card">
                @Html.Partial("_partialSupportCard",Model.bLSupport)
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script>
    $(document).ready(function () {
        $(".navigationli").removeClass("selected");
        $("#contactInfoli").addClass("selected");
         $(".select2").select2();
        if ('@ViewData["SuccessCompany"]' != null&&'@ViewData["SuccessCompany"]' != '') {
            toastr.success('@ViewData["SuccessCompany"]', 'Success');
        }
        if ('@ViewData["FailedCompany"]' != null&&'@ViewData["FailedCompany"]' != '') {
            toastr.error('@ViewData["FailedCompany"]', 'Error');
        }
        $('#DOB').datepicker({
            autoclose: true,
            todayHighlight: true
        });
    });

    function OnSuccess(response) {
        toastr.success('Data Submitted successfully!', 'Success');
    }
    function OnFailure(response) {
     toastr.error("Error occured.", 'Error');
    }
    </script>
}

Easycase.Web/Views/Setting/_partialAccount.cshtml
@model Easycase.Model.Setting.BLClientAccount

<table id="bankDetails">
    <thead>
        <tr><th>Banking Institution Name</th><th>Currency</th></tr>
    </thead>
    <tbody>
        @if (Model.BankNameArray.Length > 0)
        {
            for (int i = 0; i < Model.BankNameArray.Length; i++)
            {
                <tr>
                    <td><input type="text" value="@Model.BankNameArray[i]" class="form-control data-bank" /></td>
                    <td><input type="text" value="@Model.CurrencyArray[i]" class="form-control data-currency" /></td>

                    <td class="remove-control" style="width:20px">
                        @if (i == 0)
                        {
                            <i class="fa fa-minus-circle" aria-hidden="true"></i>
                        }
                        else
                        {
                            <i class="fa fa-minus-circle" style="color:red" onclick="RemoveRow(this)" aria-hidden="true"></i>
                        }
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td><input type="text" value="" class="form-control data-bank" /></td>
                <td><input type="text" value="" class="form-control data-currency" /></td>
                <td class="remove-control" style="width:20px">
                    <i class="fa fa-minus-circle" aria-hidden="true"></i>
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="5">
                <span onclick="AddRow()" style="float:right; color:#0088cc;text-decoration:none; cursor:pointer"><i class="fa fa-plus-square" style="font-size:1.3em;"></i> Add another row for more information</span>
            </td>
        </tr>
    </tfoot>
</table>