Easycase.Web/Models/ManageViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;

namespace Easycase.Web.Models
{
    public class IndexViewModel
    {
        public bool HasPassword { get; set; }
        public IList<UserLoginInfo> Logins { get; set; }
        public string PhoneNumber { get; set; }
        public bool TwoFactor { get; set; }
        public bool BrowserRemembered { get; set; }
    }

    public class ManageLoginsViewModel
    {
        public IList<UserLoginInfo> CurrentLogins { get; set; }
        public IList<AuthenticationDescription> OtherLogins { get; set; }
    }

    public class FactorViewModel
    {
        public string Purpose { get; set; }
    }

    public class SetPasswordViewModel
    {
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class ChangePasswordViewModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class AddPhoneNumberViewModel
    {
        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public string Number { get; set; }
    }

    public class VerifyPhoneNumberViewModel
    {
        [Required]
        [Display(Name = "Code")]
        public string Code { get; set; }

        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }
    }

    public class ConfigureTwoFactorViewModel
    {
        public string SelectedProvider { get; set; }
        public ICollection<System.Web.Mvc.SelectListItem> Providers { get; set; }
    }
}

Easycase.Web/Controllers/CalendarController.cs
using Easycase.Extension;
using Easycase.Model.Calendar;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Easycase.Web.Controllers
{
    [Authorize]
    [HandleError]
    public class CalendarController : BaseController
    {
        BLManageHours manageHours = new BLManageHours();
        BLBusinessHours businessHours = new BLBusinessHours();
        BLHolidays holidays = new BLHolidays();
        // GET: Calendar
        public ActionResult Index()
        {
            BLCalendar bLCalendar = new BLCalendar();
            var userId = User.Identity.GetUserId();
            var holiday = holidays.GetById(userId, DateTime.Now.Year);
            if (holiday != null)
            {
                holiday.HolidayList = JsonConvert.DeserializeObject<List<string>>(holiday.HolidayOfYear);
                holiday.HolidayDateList = JsonConvert.DeserializeObject<List<DateTime>>(holiday.HolidayDates);
            }
            bLCalendar.bLHolidays = holiday;
            return View(bLCalendar);
        }

        public PartialViewResult CalendarPartial()
        {
            var userId = User.Identity.GetUserId();
            var holiday = holidays.GetById(userId, DateTime.Now.Year);
            if (holiday != null)
            {
                holiday.HolidayList = JsonConvert.DeserializeObject<List<string>>(holiday.HolidayOfYear);
                holiday.HolidayDateList = JsonConvert.DeserializeObject<List<DateTime>>(holiday.HolidayDates);
                List<BLCalendarBindJsonModal> bLCalendarBindJsonModals = new List<BLCalendarBindJsonModal>();
                foreach (var item in holiday.HolidayDateList)
                {
                    BLCalendarBindJsonModal bLCalendarBindJsonModal = new BLCalendarBindJsonModal();
                    bLCalendarBindJsonModal.title = "Holiday";
                    bLCalendarBindJsonModal.start = item.ToString("yyyy-MM-dd");
                    bLCalendarBindJsonModals.Add(bLCalendarBindJsonModal);
                }
                holiday.BLCalendarBindJson = bLCalendarBindJsonModals;
            }
            return PartialView("_partialCalendar", holiday);
        }

        public ActionResult Manage()
        {
            var userId = User.Identity.GetUserId();
            BLBusinessHoursModal bLBusinessHoursModal = new BLBusinessHoursModal();
            var result = manageHours.GetAll(userId);
            var timeList = Common.GetTimeIntervals();
            ViewBag.TimeInterval = new SelectList(timeList);
            var ConsultingSession = Common.GetConsultinghours();
            ViewBag.ConsultingSessionList = new SelectList(ConsultingSession, "Value", "Text");
            var WaitTimes = Common.GetWaitingHours();
            ViewBag.WaitTimeList = new SelectList(WaitTimes, "Value", "Text");
            var LeadHours = Common.GetLeadHours();
            ViewBag.LeadHoursList = new SelectList(LeadHours);
            // Get business hours
            var businessHour = businessHours.GetById(userId);
            bLBusinessHoursModal.BusinessHourId = businessHour != null ? businessHour.ID : 0;
            bLBusinessHoursModal.ConsultingSession = businessHour != null ? businessHour.ConsultingDuration : 0;
            bLBusinessHoursModal.WaitTime = businessHour != null ? businessHour.WaitTime : 0;
            bLBusinessHoursModal.LeadDays = businessHour != null ? businessHour.LeadDays : 0;
            bLBusinessHoursModal.bLManageHours = result;

            // get holidays
            var holiday = holidays.GetById(userId, DateTime.Now.Year);
            if (holiday != null)
                holiday.HolidayList = JsonConvert.DeserializeObject<List<string>>(holiday.HolidayOfYear);
            else
                holiday = new BLHolidays();
            bLBusinessHoursModal.bLHolidays = holiday;
            return View(bLBusinessHoursModal);
        }
        [HttpPost]
        public ActionResult SaveManageHours(BLManageSaveModal modal)
        {
            try
            {
                var userId = User.Identity.GetUserId();
                // Save Manage Hours
                var result = modal.Update(userId);
                // Save Business Hours
                BLBusinessHours bLBusinessHours = new BLBusinessHours()
                {
                    ConsultingDuration = modal.ConsultingSession,
                    LeadDays = modal.LeadDays,
                    WaitTime = modal.WaitTime,
                    CreatedBy = userId,
                    ID = modal.BusinessHourId
                };
                if (bLBusinessHours.ID > 0)
                {
                    bLBusinessHours.Update();
                }
                else
                {
                    bLBusinessHours.Save();
                }
                return Json(result.Item2, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult SaveHolidays(int day, int month)
        {
            List<string> holidaymonths = new List<string>();
            List<DateTime> holidaydates = new List<DateTime>();
            string smonth = CultureInfo.CurrentCulture.DateTimeFormat.GetMonthName(month) + " " + day;
            DateTime dt = new DateTime(DateTime.Now.Year, month, day);
            holidaymonths.Add(smonth);
            holidaydates.Add(dt);
            var userId = User.Identity.GetUserId();
            var holiday = holidays.GetById(userId, DateTime.Now.Year);
            if (holiday == null)
            {
                holiday = new BLHolidays()
                {
                    CreatedBy = userId,
                    HolidayOfYear = JsonConvert.SerializeObject(holidaymonths),
                    Year = DateTime.Now.Year,
                    HolidayDates= JsonConvert.SerializeObject(holidaydates),
                };
                holiday.Save();
            }
            else
            {
                holiday.HolidayList = JsonConvert.DeserializeObject<List<string>>(holiday.HolidayOfYear);
                holiday.HolidayList.Add(smonth);
                holiday.HolidayOfYear = JsonConvert.SerializeObject(holiday.HolidayList);

                holiday.HolidayDateList = JsonConvert.DeserializeObject<List<DateTime>>(holiday.HolidayDates);
                holiday.HolidayDateList.Add(dt);
                holiday.HolidayDates = JsonConvert.SerializeObject(holiday.HolidayDateList);
                var anyDuplicate = holiday.HolidayDateList.GroupBy(x => x).Any(g => g.Count() > 1);
                if (!anyDuplicate)
                {
                    holiday.Update();
                }
            }
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        public ActionResult HolidayPartial()
        {
            var userId = User.Identity.GetUserId();
            var holiday = holidays.GetById(userId, DateTime.Now.Year);
            if (holiday != null)
                holiday.HolidayList = JsonConvert.DeserializeObject<List<string>>(holiday.HolidayOfYear);
            return PartialView("_partialHolidays", holiday);
        }
        //public ActionResult GetCalendarData()
        //{
        //    // Initialization.  
        //    JsonResult result = new JsonResult();

        //    try
        //    {
        //        // Loading.  
        //        var userId = User.Identity.GetUserId();
        //        var holiday = holidays.GetById(userId, DateTime.Now.Year);
        //        if (holiday != null)
        //        {
        //            holiday.HolidayList = JsonConvert.DeserializeObject<List<string>>(holiday.HolidayOfYear);
        //            holiday.HolidayDateList = JsonConvert.DeserializeObject<List<DateTime>>(holiday.HolidayDates);
        //        }

        //        // Processing.  
        //        result = this.Json(holiday, JsonRequestBehavior.AllowGet);
        //    }
        //    catch (Exception ex)
        //    {
        //        // Info  
        //        Console.Write(ex);
        //    }

        //    // Return info.  
        //    return result;
        //}

        public ActionResult RemoveHolidays(string date) 
        {
            List<string> holidaymonths = new List<string>();
            var userId = User.Identity.GetUserId();
            var holiday = holidays.GetById(userId, DateTime.Now.Year);
            if (holiday != null)
            {
                holiday.HolidayList = JsonConvert.DeserializeObject<List<string>>(holiday.HolidayOfYear);
                int index = holiday.HolidayList.IndexOf(date);
                holiday.HolidayList.Remove(date);
                holiday.HolidayOfYear = JsonConvert.SerializeObject(holiday.HolidayList);

                holiday.HolidayDateList = JsonConvert.DeserializeObject<List<DateTime>>(holiday.HolidayDates);
                holiday.HolidayDateList.RemoveAt(index);
                holiday.HolidayDates = JsonConvert.SerializeObject(holiday.HolidayDateList);
                holiday.Update();
            }
            return Json(true, JsonRequestBehavior.AllowGet);
        }
    }
}

Easycase.Web/Views/Calendar/Index.cshtml
@model Easycase.Model.Calendar.BLCalendar
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Styles.Render("~/Content/calendar")
@Scripts.Render("~/bundles/calendar")
<div class="page-breadcrumb">
    <div class="row">
        <div class="col-12 d-flex no-block align-items-center">
            <h4 class="page-title">Calendar</h4>
            <div class="ml-auto text-right">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Library</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<!-- ============================================================== -->
<!-- End Bread crumb and right sidebar toggle -->
<!-- ============================================================== -->
<!-- ============================================================== -->
<!-- Container fluid  -->
<!-- ============================================================== -->
<div class="container-fluid">
    <!-- ============================================================== -->
    <!-- Start Page Content -->
    <!-- ============================================================== -->
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="">
                    <div class="row">
                        <div class="col-lg-3 border-right p-r-0">
                            <div class="card-body border-bottom">
                                <h4 class="card-title m-t-10">Drag & Drop Event</h4>
                            </div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div id="calendar-events" class="">
                                            <div class="calendar-events m-b-20" data-class="bg-info"><i class="fa fa-circle text-info m-r-10"></i>Event One</div>
                                            <div class="calendar-events m-b-20" data-class="bg-success"><i class="fa fa-circle text-success m-r-10"></i> Event Two</div>
                                            <div class="calendar-events m-b-20" data-class="bg-danger"><i class="fa fa-circle text-danger m-r-10"></i>Event Three</div>
                                            <div class="calendar-events m-b-20" data-class="bg-warning"><i class="fa fa-circle text-warning m-r-10"></i>Event Four</div>
                                        </div>
                                        <!-- checkbox -->
                                        <div class="custom-control custom-checkbox">
                                            <input type="checkbox" class="custom-control-input" id="drop-remove">
                                            <label class="custom-control-label" for="drop-remove">Remove after drop</label>
                                        </div>
                                        <a href="javascript:void(0)" data-toggle="modal" data-target="#add-new-event" class="btn m-t-20 btn-info btn-block waves-effect waves-light">
                                            <i class="ti-plus"></i> Add New Event
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-9">
                            <div class="card-body b-l calender-sidebar">
                                @{Html.RenderAction("CalendarPartial", "Calendar"); }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- BEGIN MODAL -->
    <div class="modal none-border" id="my-event">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title"><strong>Add Event</strong></h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <div class="modal-body"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary waves-effect" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-success save-event waves-effect waves-light">Create event</button>
                    <button type="button" class="btn btn-danger delete-event waves-effect waves-light" data-dismiss="modal">Delete</button>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal Add Category -->
    <div class="modal fade none-border" id="add-new-event">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title"><strong>Add</strong> a category</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="row">
                            <div class="col-md-6">
                                <label class="control-label">Category Name</label>
                                <input class="form-control form-white" placeholder="Enter name" type="text" name="category-name" />
                            </div>
                            <div class="col-md-6">
                                <label class="control-label">Choose Category Color</label>
                                <select class="form-control form-white" data-placeholder="Choose a color..." name="category-color">
                                    <option value="success">Success</option>
                                    <option value="danger">Danger</option>
                                    <option value="info">Info</option>
                                    <option value="primary">Primary</option>
                                    <option value="warning">Warning</option>
                                    <option value="inverse">Inverse</option>
                                </select>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger waves-effect waves-light save-category" data-dismiss="modal">Save</button>
                    <button type="button" class="btn btn-secondary waves-effect" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <!-- END MODAL -->
    <!-- ============================================================== -->
    <!-- End PAge Content -->
    <!-- ============================================================== -->
</div>
@section Scripts {
    <script>
        $(document).ready(function () {
            $(".navigationli").removeClass("selected");
            $("#calendarli").addClass("selected");
        });
    </script>
}

Easycase.Web/Views/Calendar/Manage.cshtml
@model Easycase.Model.Calendar.BLBusinessHoursModal
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Styles.Render("~/Content/datatable")
<div class="page-breadcrumb">
    <div class="row">
        <div class="col-12 d-flex no-block align-items-center">
            <h4 class="page-title">Manage Business Hours</h4>
            <div class="ml-auto text-right">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Clients</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title m-b-0"></h5>
                </div>
                <div class="table-responsive">
                    <table class="table" id="manageTable">
                        <thead class="thead-light">
                            <tr>
                                <th scope="col">
                                    Consulting Days
                                </th>
                                <th scope="col">Start Time</th>
                                <th scope="col">End Time</th>
                                <th scope="col">Lunch Start Time</th>
                                <th scope="col">Lunch End Time</th>
                            </tr>
                        </thead>
                        <tbody class="customtable">
                            @foreach (var item in Model.bLManageHours)
                            {
                                <tr id="@item.ID">
                                    <td>
                                        <label class="customcheckbox">
                                            <input type="checkbox" checked="@item.IsActive" class="listCheckbox" />
                                            <span class="checkmark"></span>
                                            <span>@item.Day</span>
                                        </label>
                                    </td>
                                    <td>@Html.DropDownList(item.StartTime, ViewBag.TimeInterval as SelectList, new { @class = "select2 form-control custom-select startime", @id = "_startTime" + item.ID })</td>
                                    <td>@Html.DropDownList(item.EndTime, ViewBag.TimeInterval as SelectList, new { @class = "select2 form-control custom-select endtime", @id = "_endTime" + item.ID })</td>
                                    <td>@Html.DropDownList(item.LunchStartTime, ViewBag.TimeInterval as SelectList, new { @class = "select2 form-control custom-select lunchstarttime", @id = "_sLunchStartTime" + item.ID })</td>
                                    <td>@Html.DropDownList(item.LunchEndTime, ViewBag.TimeInterval as SelectList, new { @class = "select2 form-control custom-select lunchendtime", @id = "_eLunchEndTime" + item.ID })</td>
                                </tr>
                                <script>
                                    $('#_startTime' +@item.ID).val('@item.StartTime');
                                    $('#_endTime' +@item.ID).val('@item.EndTime');
                                    $('#_sLunchStartTime' +@item.ID).val('@item.LunchStartTime');
                                    $('#_eLunchEndTime' +@item.ID).val('@item.LunchEndTime');
                                </script>
                            }
                        </tbody>
                    </table>
                </div>
                <form class="form-horizontal">
                    <div class="card-body">
                        @Html.HiddenFor(model => model.BusinessHourId)
                        <div class="form-group row">
                            <div class="col-sm-6">
                                <label class="control-label col-md-6">Average Consulting Session Duration </label>
                                <div class="col-sm-12">
                                    @Html.DropDownListFor(modal => modal.ConsultingSession, ViewBag.ConsultingSessionList as SelectList, new { @class = "select2 form-control custom-select ConsultingSession" })
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <label class="control-label col-md-6">Average wait time between consulting sessions</label>
                                <div class="col-sm-12">
                                    @Html.DropDownListFor(modal => modal.WaitTime, ViewBag.WaitTimeList as SelectList, new { @class = "select2 form-control custom-select ConsultingSession" })
                                </div>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-6">
                                <label class="control-label col-md-6">Average lead days required for consulting session</label>
                                <div class="col-sm-12">
                                    @Html.DropDownListFor(modal => modal.LeadDays, ViewBag.LeadHoursList as SelectList, new { @class = "select2 form-control custom-select LeadDays" })
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="card-body">
                        <div class="col-sm-6">
                            <label class="control-label col-md-6"><i class="fa fa-calendar" aria-hidden="true"></i> Enter all holidays for the year </label>
                            <div class="col-sm-12">
                                <input type="text" class="date-inputmask" style="width:300px" id="holidays" />
                                <button type="button" onclick="UpdateHoliday()" class="btn btn-default">Update</button>
                            </div>
                        </div>
                        <div id="holidayDiv" class="col-sm-12">
                            @Html.Partial("_partialHolidays", Model.bLHolidays)
                        </div>
                    </div>
                    <div class="border-top">
                        <div class="card-body">
                            <button type="button" onclick="AddHours()" class="btn btn-primary">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/datatables")
    <script>
        $(document).ready(function () {
            $(".navigationli").removeClass("selected");
            $("#calendarli").addClass("selected");
            $(".select2").select2();
             $('#holidays').datepicker({
                autoclose: true,
                todayHighlight: true
            });
        });
        $('#manageTable').dataTable(
            {
                "bSort": false,
                "info": false,
                "paging": false,
                "searching": false
            });


        function AddHours() {
            var startimes = [];
            var endtimes = [];
            var lunchstarttimes = [];
            var lunchendtimes = [];
            var isactive = [];
            var ids = [];
            $("#manageTable tbody tr").each(function (index, value) {
                startimes.push($(value).find(".startime").val());
                endtimes.push($(value).find(".endtime").val());
                lunchstarttimes.push($(value).find(".lunchstarttime").val());
                lunchendtimes.push($(value).find(".lunchendtime").val());
                ids.push($(value).attr("id"));
                isactive.push($(value).find(".listCheckbox").prop("checked"));
            });
            var data = new Object();
            data.IsActive = isactive;
            data.ID = ids;
            data.StartTime = startimes;
            data.EndTime = endtimes;
            data.LunchStartTime = lunchstarttimes;
            data.LunchEndTime = lunchendtimes;
            data.ConsultingSession = $("#ConsultingSession").val();
            data.WaitTime = $("#WaitTime").val();
            data.LeadDays = $("#LeadDays").val();
            data.BusinessHourId = $("#BusinessHourId").val();
            $.ajax({
                url: "/Calendar/SaveManageHours",
                type: "POST",
                data: data,
                success: function (response) {
                    toastr.success(response, 'Success');
                },
                error: function (er) {
                    toastr.error(er, 'Error');
                }
            });
        }
        
        function UpdateHoliday() {
            var date = $("#holidays").val();
            var d = new Date(date);
            var day = addZero(d.getDate());
            var month = addZero((d.getMonth() + 1));
            $.ajax({
                url: "/Calendar/SaveHolidays",
                type: "POST",
                data: { day: day, month: month },
                success: function (response) {
                    $.ajax({
                        url: "/Calendar/HolidayPartial",
                        type: "GET",
                        success: function (response) {
                            $("#holidayDiv").empty().html(response);
                            $("#holidays").val("");
                        },
                        error: function (er) {
                            toastr.error(er, 'Error');
                        }
                    });
                },
                error: function (er) {
                    toastr.error(er, 'Error');
                }
            });
        }

        function RemoveDataEntry(date)
        {
            $.ajax({
                url: "/Calendar/RemoveHolidays",
                type: "POST",
                data: { date: date },
                success: function (response) {
                    $.ajax({
                        url: "/Calendar/HolidayPartial",
                        type: "GET",
                        success: function (response) {
                            $("#holidayDiv").empty().html(response);
                            $("#holidays").val("");
                        },
                        error: function (er) {
                            toastr.error(er, 'Error');
                        }
                    });
                },
                error: function (er) {
                    toastr.error(er, 'Error');
                }
            });
        }
    </script>
}

Easycase.Web/Views/Calendar/_partialCalendar.cshtml
@model Easycase.Model.Calendar.BLHolidays
<div id="calendar"></div>

<script>

    document.addEventListener('DOMContentLoaded', function () {
        var calendarEl = document.getElementById('calendar');

        var calendar = new FullCalendar.Calendar(calendarEl, {
            headerToolbar: {
                left: 'prev,next today',
                center: 'title',
                right: 'dayGridMonth,timeGridWeek,timeGridDay,listWeek'
            },
            initialDate: '2020-09-12',
            navLinks: true, // can click day/week names to navigate views
            nowIndicator: true,

            weekNumbers: true,
            weekNumberCalculation: 'ISO',

            editable: true,
            selectable: true,
            dayMaxEvents: true, // allow "more" link when too many events
            events:@Html.Raw(Json.Encode(Model.BLCalendarBindJson)),
        });

        calendar.render();
    });

</script>

Easycase.Web/Views/Calendar/_partialHolidays.cshtml
@model Easycase.Model.Calendar.BLHolidays

<div class="row">
    @if (Model.HolidayList != null)
    {
        foreach (var item in Model.HolidayList)
        {
            string holiday = item.Replace(" ", "");
            <div id="@holiday" style="width:180px;margin-left:10px;margin-top:10px" class="span3 alert alert-info"> <button type="button" class="close" onclick="RemoveDataEntry('@item')" data-dismiss="alert">×</button>@item</div>
        }
    }
</div>